### PR TITLE
Support For Swift

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Support For Swift Added 
#10

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer cannot find image locally error in Travis.
screenshot 2018-07-07 at 1 07 36 am

**Comment by championswimmer** [comment]
the docker image is not built
```

 ---> Running in f5cd19d067c9
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  swift (missing):
    required by: world[swift=4.0]
The command '/bin/sh -c apk add --no-cache swift=4.0 bash' returned a non-zero code: 1
```

you need to fix the Dockerfile

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya there is no support for alpine 3.6 for swift either we have to go with alpine 3.1 or above 4.0

**Comment by championswimmer** [comment]
make it based on this image then https://github.com/swiftdocker/docker-swift

**Pull request closed without merging**
