### PR TITLE
Kotlin moved to judge-worker

### LINKED ISSUE #45: move kotlin into judge worker

### PR DESCRIPTION
**Pull request by HeroicHitesh**
Resolves #45

### CODE REVIEW

**Comment by championswimmer** [comment]
should fix the test too

**Comment by HeroicHitesh** [comment]
@championswimmer required changes made.

**Comment by championswimmer** [comment]
still failing 👀

**Comment by championswimmer** [comment]
this needs to be fixed 

image

**Comment by HeroicHitesh** [comment]
This should work now. @championswimmer please check it out.

**Comment by HeroicHitesh** [comment]
@championswimmer Should I change README.md too, by adding Kotlin to it?

**Comment by championswimmer** [comment]
Yeah add on readme too

**Comment by HeroicHitesh** [comment]
@championswimmer done. While adding `kotlin` to README.md I found that all other language links are invalid and result in 404. Should I update them in this PR or open another PR as they are not related to the issue this PR resolves?

**Comment by jatinkatyal13** [comment]
Tests are still failing. You'll need to allocate more memory while running the test. Just update the test file [here](https://github.com/coding-blocks/judge-workers/blob/master/tests/judge-worker/test_workers.sh#L17)

**Comment by HeroicHitesh** [comment]
> You'll need to allocate more memory while running the test.

@jatinkatyal13 Will `--memory="200m" ` be sufficient?

**Comment by HeroicHitesh** [comment]
@jatinkatyal13 it seems #45 is resolved now.

**Pull request merged**
