### PR TITLE
added Support For Ruby

### LINKED ISSUE #4: add support for Ruby
- [ ] add the docker container and compile + run scripts here
- [ ] add run spec test on taskmaster https://github.com/coding-blocks/judge-taskmaster/issues/11

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
fix #4

### CODE REVIEW

**Comment by championswimmer** [comment]
please remove DS_Store files

**Comment by aggarwalpulkit596** [comment]
will do that in a moment @championswimmer

**Comment by aggarwalpulkit596** [comment]
@championswimmer done

**Comment by aggarwalpulkit596** [comment]
@championswimmer sub part of this pr https://github.com/coding-blocks/judge-taskmaster/pull/12

**Pull request closed without merging**
