### PR TITLE
Add support for csharp

### LINKED ISSUE #3: add support for C# (csharp)
- [ ] add the docker container and compile + run scripts here
- [ ] add run spec test on taskmaster https://github.com/coding-blocks/judge-taskmaster/issues/10

### PR DESCRIPTION
**Pull request by kapillamba4**
Fixes #3

### CODE REVIEW

**Comment by kapillamba4** [comment]
Using alpine:edge instead of alpine:3.6 because mono is available only in alpine:edge
http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/

**Comment by kapillamba4** [comment]
@championswimmer review please

**Comment by kapillamba4** [comment]
PR for subtask 2: https://github.com/coding-blocks/judge-taskmaster/pull/15

**Comment by championswimmer** [comment]
@kapillamba4 please redo this with tests support :)

**Comment by kapillamba4** [comment]
Updated the PR :+1:

**Pull request merged**
